adding info on eat Packages
iqb-research/IQB-Methods pull request #12
Opened 2023-09-29 09:26 UTC by grewered

2023-09-29 13:41 UTC, grewered commented
I added Info on all the eat packages to the website. Can you have a look and give Feedback on it?
Is it better to have a single section for each package or is better to have all the info on one page?
is the layout ok?

I still have to translate all the content to English.

2023-10-13 14:35 UTC, nickhaf commented
> @nickhaf I added Info on all the eat packages to the website. Can you have a look and give Feedback on it? Is it better to have a single section for each package or is better to have all the info on one page? is the layout ok?

I like the current structure, and also the layout, so I think we can keep it at that for now!

2023-10-13 14:44 UTC, nickhaf requested changes
Looks great, thank you! Just a minor comment, then we can merge.

2023-10-13 14:44 UTC, nickhaf commented on _quarto.yml
Maybe we could sort the packages alphabetically?

2023-10-18 12:06 UTC, grewered commented
@nickhaf shall I merge then, when the check is through?

2023-10-19 12:17 UTC, merged

2023-10-19 14:55 UTC, nickhaf commented
Great, thanks!